using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KmnlkUMSEngine.Constants
{
    public static class PROCEDURES
    {
        //------------------------- Add -------------------------
        public static string Adddelegation = "Adddelegation";
        public static string Adddepartmentprivilage = "Adddepartmentprivilage";
        public static string AddDepartment = "AddDepartment";
        public static string Adddepartmentcontact = "Adddepartmentcontact";
        public static string AddDepartmentposition = "AddDepartmentposition";
        public static string Adddepartmentpositionattachment = "Adddepartmentpositionattachment";
        public static string Adddepartmentpositionnote = "Adddepartmentpositionnote";
        public static string Adddepartmentresponsipility = "Adddepartmentresponsipility";
        public static string Addoperation = "Addoperation";
        public static string Addposition = "Addposition";
        public static string Addpositioncontact = "Addpositioncontact";
        public static string Addpositionprivilage = "Addpositionprivilage";
        public static string Addpositionresponsipility = "Addpositionresponsipility";
        public static string Addprivilage = "Addprivilage";
        public static string Addprofile = "Addprofile";
        public static string AddRole = "AddRole";
        public static string Addrolecontact = "Addrolecontact";
        public static string AddRoleposition = "AddRoleposition";
        public static string Addrolepositionattachment = "Addrolepositionattachment";
        public static string Addrolepositionnote = "Addrolepositionnote";
        public static string Addroleprivilage = "Addroleprivilage";
        public static string Addroleresponsipility = "Addroleresponsipility";
        public static string AddSettings = "AddSettings";
        public static string AddUser = "AddUser";
        public static string AdduserAttachment = "AdduserAttachment";
        public static string Addusercontact = "Addusercontact";
        public static string Addusermac = "Addusermac";
        public static string Addprofilefield = "Addprofilefield";
        public static string AdduserNote = "AdduserNote";
        public static string Adduserposition = "Adduserposition";
        public static string AdduserpositionAttachment = "AdduserpositionAttachment";
        public static string Adduserpositionnote = "Adduserpositionnote";

        //------------------------- Delete -------------------------
        public static string Deletedelegation = "Deletedelegation";
        public static string Deletedepartmentprivilage = "Deletedepartmentprivilage";
        public static string DeleteDepartment = "DeleteDepartment";
        public static string Deletedepartmentcontact = "Deletedepartmentcontact";
        public static string DeleteDepartmentposition = "DeleteDepartmentposition";
        public static string Deletedepartmentpositionattachment = "Deletedepartmentpositionattachment";
        public static string Deletedepartmentpositionnote = "Deletedepartmentpositionnote";
        public static string Deletedepartmentresponsipility = "Deletedepartmentresponsipility";
        public static string Deleteoperation = "Deleteoperation";
        public static string Deleteposition = "Deleteposition";
        public static string Deletepositioncontact = "Deletepositioncontact";
        public static string Deletepositionprivilage = "Deletepositionprivilage";
        public static string Deletepositionresponsipility = "Deletepositionresponsipility";
        public static string Deleteprivilage = "Deleteprivilage";
        public static string Deleteprofile = "Deleteprofile";
        public static string DeleteRole = "DeleteRole";
        public static string Deleterolecontact = "Deleterolecontact";
        public static string DeleteRoleposition = "DeleteRoleposition";
        public static string Deleterolepositionattachment = "Deleterolepositionattachment";
        public static string Deleterolepositionnote = "Deleterolepositionnote";
        public static string Deleteroleprivilage = "Deleteroleprivilage";
        public static string Deleteroleresponsipility = "Deleteroleresponsipility";
        public static string DeleteSettings = "DeleteSettings";
        public static string DeleteUser = "DeleteUser";
        public static string DeleteuserAttachment = "DeleteuserAttachment";
        public static string Deleteusercontact = "Deleteusercontact";
        public static string Deleteusermac = "Deleteusermac";
        public static string Deleteprofilefield = "Deleteprofilefield";
        public static string DeleteuserNote = "DeleteuserNote";
        public static string Deleteuserposition = "Deleteuserposition";
        public static string DeleteuserpositionAttachment = "DeleteuserpositionAttachment";
        public static string Deleteuserpositionnote = "Deleteuserpositionnote";

        //------------------------- Edit -------------------------
        public static string Editdelegation = "Editdelegation";
        public static string Editdepartmentprivilage = "Editdepartmentprivilage";
        public static string EditDepartment = "EditDepartment";
        public static string Editdepartmentcontact = "Editdepartmentcontact";
        public static string EditDepartmentposition = "EditDepartmentposition";
        public static string Editdepartmentpositionattachment = "Editdepartmentpositionattachment";
        public static string Editdepartmentpositionnote = "Editdepartmentpositionnote";
        public static string Editdepartmentresponsipility = "Editdepartmentresponsipility";
        public static string Editoperation = "Editoperation";
        public static string Editposition = "Editposition";
        public static string Editpositioncontact = "Editpositioncontact";
        public static string Editpositionprivilage = "Editpositionprivilage";
        public static string Editpositionresponsipility = "Editpositionresponsipility";
        public static string Editprivilage = "Editprivilage";
        public static string Editprofile = "Editprofile";
        public static string EditRole = "EditRole";
        public static string Editrolecontact = "Editrolecontact";
        public static string EditRoleposition = "EditRoleposition";
        public static string Editrolepositionattachment = "Editrolepositionattachment";
        public static string Editrolepositionnote = "Editrolepositionnote";
        public static string Editroleprivilage = "Editroleprivilage";
        public static string Editroleresponsipility = "Editroleresponsipility";
        public static string EditSettings = "EditSettings";
        public static string EditUser = "EditUser";
        public static string EdituserAttachment = "EdituserAttachment";
        public static string Editusercontact = "Editusercontact";
        public static string Editusermac = "Editusermac";
        public static string Editprofilefield = "Editprofilefield";
        public static string EdituserNote = "EdituserNote";
        public static string Edituserposition = "Edituserposition";
        public static string EdituserpositionAttachment = "EdituserpositionAttachment";
        public static string Edituserpositionnote = "Edituserpositionnote";

        //------------------------- Get -------------------------
        public static string GetAlldelegations = "GetAlldelegations";
        public static string GetAlldepartmentsprivilages = "GetAlldepartmentsprivilages";
        public static string GetAlldepartments = "GetAlldepartments";
        public static string GetAlldepartmentscontacts = "GetAlldepartmentscontacts";
        public static string GetAlldepartmentspositions = "GetAlldepartmentspositions";
        public static string GetAlldepartmentspositionsattachments = "GetAlldepartmentspositionsattachments";
        public static string GetAlldepartmentspositionsnotes = "GetAlldepartmentspositionsnotes";
        public static string GetAlldepartmentsresponsipilities = "GetAlldepartmentsresponsipilities";
        public static string GetAlloperations = "GetAlloperations";
        public static string GetAllpositions = "GetAllpositions";
        public static string GetAllpositionscontacts = "GetAllpositionscontacts";
        public static string GetAllpositionsprivilages = "GetAllpositionsprivilages";
        public static string GetAllpositionsresponsipilities = "GetAllpositionsresponsipilities";
        public static string GetAllprivilages = "GetAllprivilages";
        public static string GetAllprofiles = "GetAllprofiles";
        public static string GetAllprofilesfields = "GetAllprofilesfields";
        public static string GetAllRoles = "GetAllRoles";
        public static string GetAllrolescontacts = "GetAllrolescontacts";
        public static string GetAllRolespositions = "GetAllRolespositions";
        public static string GetAllrolespositionsattachments = "GetAllrolespositionsattachments";
        public static string GetAllrolespositionsnotes = "GetAllrolespositionsnotes";
        public static string GetAllrolesprivilages = "GetAllrolesprivilages";
        public static string GetAllrolesresponsipilities = "GetAllrolesresponsipilities";
        public static string GetAllSettings = "GetAllSettings";
        public static string GetAllUsers = "GetAllUsers";
        public static string GetAllusersAttachments = "GetAllusersAttachments";
        public static string GetAlluserscontacts = "GetAlluserscontacts";
        public static string GetAllusersmacs = "GetAllusersmacs";
        public static string GetAllusersNotes = "GetAllusersNotes";
        public static string GetAlluserspositions = "GetAlluserspositions";
        public static string GetAlluserspositionsattachments = "GetAlluserspositionsattachments";
        public static string GetAlluserspositionsnotes = "GetAlluserspositionsnotes";

        //------------------------- Find -------------------------
        public static string FindAlldelegations = "FindAlldelegations";
        public static string FindAlldepartmentsprivilages = "FindAlldepartmentsprivilages";
        public static string FindAlldepartments = "FindAlldepartments";
        public static string FindAlldepartmentscontacts = "FindAlldepartmentscontacts";
        public static string FindAlldepartmentspositions = "FindAlldepartmentspositions";
        public static string FindAlldepartmentspositionsattachments = "FindAlldepartmentspositionsattachments";
        public static string FindAlldepartmentspositionsnotes = "FindAlldepartmentspositionsnotes";
        public static string FindAlldepartmentsresponsipilities = "FindAlldepartmentsresponsipilities";
        public static string FindAlloperations = "FindAlloperations";
        public static string FindAllpositions = "FindAllpositions";
        public static string FindAllpositionscontacts = "FindAllpositionscontacts";
        public static string FindAllpositionsprivilages = "FindAllpositionsprivilages";
        public static string FindAllpositionsresponsipilities = "FindAllpositionsresponsipilities";
        public static string FindAllprivilages = "FindAllprivilages";
        public static string FindAllprofiles = "FindAllprofiles";
        public static string FindAllprofilesfields = "FindAllprofilesfields";
        public static string FindAllRoles = "FindAllRoles";
        public static string FindAllrolescontacts = "FindAllrolescontacts";
        public static string FindAllRolespositions = "FindAllRolespositions";
        public static string FindAllrolespositionsattachments = "FindAllrolespositionsattachments";
        public static string FindAllrolespositionsnotes = "FindAllrolespositionsnotes";
        public static string FindAllrolesprivilages = "FindAllrolesprivilages";
        public static string FindAllrolesresponsipilities = "FindAllrolesresponsipilities";
        public static string FindAllSettings = "FindAllSettings";
        public static string FindAllUsers = "FindAllUsers";
        public static string FindAllusersAttachments = "FindAllusersAttachments";
        public static string FindAlluserscontacts = "FindAlluserscontacts";
        public static string FindAllusersmacs = "FindAllusersmacs";
        public static string FindAllusersNotes = "FindAllusersNotes";
        public static string FindAlluserspositions = "FindAlluserspositions";
        public static string FindAlluserspositionsattachments = "FindAlluserspositionsattachments";
        public static string FindAlluserspositionsnotes = "FindAlluserspositionsnotes";


        //------------------------- Get -------------------------
        public static string GetdelegationByfromuserid = "GetdelegationByfromuserid";
        public static string GetdelegationById = "GetdelegationById";
        public static string GetdelegationBytouserid = "GetdelegationBytouserid";
        public static string GetdepartmentsprivilagesByprivilageId = "GetdepartmentsprivilagesByprivilageId";
        public static string GetdepartmentById = "GetdepartmentById";
        public static string GetdepartmentcontactById = "GetdepartmentcontactById";
        public static string GetdepartmentpositionattachmentByid = "GetdepartmentpositionattachmentByid";
        public static string GetdepartmentpositionById = "GetdepartmentpositionById";
        public static string GetdepartmentpositionBypositionidANDdepartmentId = "GetdepartmentpositionBypositionidANDdepartmentId";
        public static string GetdepartmentpositionBypositionid = "GetdepartmentpositionBypositionid";
        public static string GetdepartmentpositionBydepartmentId = "GetdepartmentpositionBydepartmentId";
        public static string GetdepartmentpositionnoteById = "GetdepartmentpositionnoteById";
        public static string GetdepartmentresponsipilityById = "GetdepartmentresponsipilityById";
        public static string GetdepartmentsBypositionId = "GetdepartmentsBypositionId";
        public static string GetdepartmentscontactsBydepartmentId = "GetdepartmentscontactsBydepartmentId";
        public static string GetdepartmentspositionsattachmentsBydepartmentpositionId = "GetdepartmentspositionsattachmentsBydepartmentpositionId";
        public static string GetdepartmentspositionsattachmentsByuserId = "GetdepartmentspositionsattachmentsByuserId";
        public static string GetdepartmentspositionsnotesBydepartmentpositionId = "GetdepartmentspositionsnotesBydepartmentpositionId";
        public static string GetdepartmentspositionsnotesByuserId = "GetdepartmentspositionsnotesByuserId";
        public static string Getdepartmentsresponsipilitiesbydepartmentid = "Getdepartmentsresponsipilitiesbydepartmentid";
        public static string GetoperationById = "GetoperationById";
        public static string GetpositionById = "GetpositionById";
        public static string GetpositioncontactById = "GetpositioncontactById";
        public static string GetpositionresponsipilityById = "GetpositionresponsipilityById";
        public static string GetpositionsBydepartmentId = "GetpositionsBydepartmentId";
        public static string GetpositionsByRoleId = "GetpositionsByRoleId";
        public static string GetpositionsByuserId = "GetpositionsByuserId";
        public static string GetpositionscontactsBypositionId = "GetpositionscontactsBypositionId";
        public static string GetpositionsprivilagesByprivilageId = "GetpositionsprivilagesByprivilageId";
        public static string Getpositionsresponsipilitiesbypositionid = "Getpositionsresponsipilitiesbypositionid";
        public static string GetpositionprivilageById = "GetpositionprivilageById";
        public static string GetdepartmentprivilageById = "GetdepartmentprivilageById";
        public static string GetroleprivilageById = "GetroleprivilageById";
        public static string GetprivilageById = "GetprivilageById";
        public static string GetprofileById = "GetprofileById";
        public static string GetprofileByUserid = "GetprofileByUserid";
        public static string GetprofilesfieldsByprofileId = "getprofilesfieldsByprofileId";
        public static string GetRoleById = "GetRoleById";
        public static string GetrolecontactById = "GetrolecontactById";
        public static string GetrolepositionattachmentByid = "GetrolepositionattachmentByid";
        public static string GetRolepositionById = "GetRolepositionById";
        public static string GetRolepositionBypositionidANDRoleId = "GetRolepositionBypositionidANDRoleId";
        public static string GetrolepositionnoteById = "GetrolepositionnoteById";
        public static string GetroleresponsipilityById = "GetroleresponsipilityById";
        public static string GetRolesBypositionId = "GetRolesBypositionId";
        public static string GetrolescontactsByroleId = "GetrolescontactsByroleId";
        public static string GetrolespositionsattachmentsByrolepositionId = "GetrolespositionsattachmentsByrolepositionId";
        public static string GetrolespositionsattachmentsByuserId = "GetrolespositionsattachmentsByuserId";
        public static string GetrolespositionsnotesByrolepositionId = "GetrolespositionsnotesByrolepositionId";
        public static string GetrolespositionsnotesByuserId = "GetrolespositionsnotesByuserId";
        public static string GetrolesprivilagesByprivilageId = "GetrolesprivilagesByprivilageId";
        public static string Getrolesresponsipilitiesbyroleid = "Getrolesresponsipilitiesbyroleid";
        public static string GetSettingsById = "GetSettingsById";
        public static string GetuserAttachmentByid = "GetuserAttachmentByid";
        public static string GetUserById = "GetUserById";
        public static string GetusercontactById = "GetusercontactById";
        public static string GetusermacById = "GetusermacById";
        public static string GetprofilefieldById = "GetprofilefieldById";
        public static string GetuserNoteById = "GetuserNoteById";
        public static string GetuserpositionAttachmentByid = "GetuserpositionAttachmentByid";
        public static string GetuserpositionById = "GetuserpositionById";
        public static string GetuserpositionBypositionidANDuserId = "GetuserpositionBypositionidANDuserId";
        public static string GetuserpositionnoteById = "GetuserpositionnoteById";
        public static string GetusersattachmentsByuserId = "GetusersattachmentsByuserId";
        public static string GetusersBypositionId = "GetusersBypositionId";
        public static string GetuserscontactsByuserId = "GetuserscontactsByuserId";
        public static string GetusersmacsByuserId = "GetusersmacsByuserId";
        public static string GetusersnotesByuserId = "GetusersnotesByuserId";
        public static string GetuserspositionsattachmentsByuserId = "GetuserspositionsattachmentsByuserId";
        public static string GetuserspositionsnotesByuserpositionId = "GetuserspositionsnotesByuserpositionId";

    }
}
